name: Pages – build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm i
          npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest  
    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v2
